# Generated by Django 6.0.4 on 2026-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre visible en el sidebar', max_length=80)),
                ('tag', models.CharField(help_text='Query enviado a la API del proveedor', max_length=80)),
                ('conteo', models.PositiveIntegerField(default=0, help_text='Cantidad referencial de videos')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
